package com.yuansewenhua.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DOODSTYPE.
 */
public class Doodstype {

    private Long id;
    private String title;

    public Doodstype() {
    }

    public Doodstype(Long id) {
        this.id = id;
    }

    public Doodstype(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
