package com.yuansewenhua.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DRINKSTYPE.
 */
public class Drinkstype {

    private Long id;
    /** Not-null value. */
    private String title;

    public Drinkstype() {
    }

    public Drinkstype(Long id) {
        this.id = id;
    }

    public Drinkstype(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

}
