package com.yuansewenhua.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FOODSTYPE.
 */
public class Foodstype {

    private Long id;
    private String title;

    public Foodstype() {
    }

    public Foodstype(Long id) {
        this.id = id;
    }

    public Foodstype(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
