package com.yuansewenhua.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDERS.
 */
public class Orders {

    private Long id;
    private java.util.Date createdate;
    private String status;
    private java.util.Date createtime;
    private java.util.Date paydate;
    private java.util.Date paytime;
    private Integer tablenumber;
    private String fromwitchpad;
    private String waitername;
    private String pricecount;
    private String memo;
    private Integer peoplenumber;
    private Long orderod;

    public Orders() {
    }

    public Orders(Long id) {
        this.id = id;
    }

    public Orders(Long id, java.util.Date createdate, String status, java.util.Date createtime, java.util.Date paydate, java.util.Date paytime, Integer tablenumber, String fromwitchpad, String waitername, String pricecount, String memo, Integer peoplenumber, Long orderod) {
        this.id = id;
        this.createdate = createdate;
        this.status = status;
        this.createtime = createtime;
        this.paydate = paydate;
        this.paytime = paytime;
        this.tablenumber = tablenumber;
        this.fromwitchpad = fromwitchpad;
        this.waitername = waitername;
        this.pricecount = pricecount;
        this.memo = memo;
        this.peoplenumber = peoplenumber;
        this.orderod = orderod;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(java.util.Date createdate) {
        this.createdate = createdate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(java.util.Date createtime) {
        this.createtime = createtime;
    }

    public java.util.Date getPaydate() {
        return paydate;
    }

    public void setPaydate(java.util.Date paydate) {
        this.paydate = paydate;
    }

    public java.util.Date getPaytime() {
        return paytime;
    }

    public void setPaytime(java.util.Date paytime) {
        this.paytime = paytime;
    }

    public Integer getTablenumber() {
        return tablenumber;
    }

    public void setTablenumber(Integer tablenumber) {
        this.tablenumber = tablenumber;
    }

    public String getFromwitchpad() {
        return fromwitchpad;
    }

    public void setFromwitchpad(String fromwitchpad) {
        this.fromwitchpad = fromwitchpad;
    }

    public String getWaitername() {
        return waitername;
    }

    public void setWaitername(String waitername) {
        this.waitername = waitername;
    }

    public String getPricecount() {
        return pricecount;
    }

    public void setPricecount(String pricecount) {
        this.pricecount = pricecount;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getPeoplenumber() {
        return peoplenumber;
    }

    public void setPeoplenumber(Integer peoplenumber) {
        this.peoplenumber = peoplenumber;
    }

    public Long getOrderod() {
        return orderod;
    }

    public void setOrderod(Long orderod) {
        this.orderod = orderod;
    }

}
