package com.yuansewenhua.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PORELATIONSHIPS.
 */
public class Porelationships {

    private Long id;
    private Long orderid;
    private Long productid;
    private String status;
    private String producttyppe;
    private Integer productcount;

    public Porelationships() {
    }

    public Porelationships(Long id) {
        this.id = id;
    }

    public Porelationships(Long id, Long orderid, Long productid, String status, String producttyppe, Integer productcount) {
        this.id = id;
        this.orderid = orderid;
        this.productid = productid;
        this.status = status;
        this.producttyppe = producttyppe;
        this.productcount = productcount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrderid() {
        return orderid;
    }

    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    public Long getProductid() {
        return productid;
    }

    public void setProductid(Long productid) {
        this.productid = productid;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getProducttyppe() {
        return producttyppe;
    }

    public void setProducttyppe(String producttyppe) {
        this.producttyppe = producttyppe;
    }

    public Integer getProductcount() {
        return productcount;
    }

    public void setProductcount(Integer productcount) {
        this.productcount = productcount;
    }

}
